"""initial 2

Revision ID: 15f0c9c5eb34
Revises: fef5726be949
Create Date: 2025-05-29 12:01:04.819466

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "15f0c9c5eb34"
down_revision: Union[str, None] = "fef5726be949"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
