apiVersion: v1
kind: Service
metadata:
  name: notifications-api
  namespace: hse-coursework-health
spec:
  selector:
    app: notifications-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: ClusterIP